ALTER TABLE MF_ORDEMDECOMPRA DROP COLUMN AUTORIZADOR;
ALTER TABLE MF_ORDEMDECOMPRA DROP COLUMN CONTRATADO;
ALTER TABLE MF_ORDEMDECOMPRA ADD (ID_USUARIO NUMBER);
ALTER TABLE MF_ORDEMDECOMPRA ADD (ID_FORNECEDOR NUMBER);
ALTER TABLE MF_ORDEMDECOMPRA ADD CONSTRAINT MF_ORDEMDECOMPRA_fk1 FOREIGN KEY (ID_USUARIO) REFERENCES SYSAID_USER (ID);
ALTER TABLE MF_ORDEMDECOMPRA ADD CONSTRAINT MF_ORDEMDECOMPRA_fk2 FOREIGN KEY (ID_FORNECEDOR) REFERENCES COMPANY (ID);


ALTER TABLE MF_MATERIAL ADD (CODIGOBARRA VARCHAR2(255));
ALTER TABLE MF_MATERIAL MODIFY (DESCRICAO VARCHAR2(255));
ALTER TABLE MF_MATERIAL MODIFY (MATERIAL VARCHAR2(255));

29/07
ALTER TABLE MF_ORDEMDECOMPRA ADD (JUSTIFICATIVA VARCHAR2(1000));

30/07
ALTER TABLE MF_NOTAFISCAL ADD (JUSTIFICATIVA VARCHAR2(1000));

31/07
CREATE TABLE
    MF_ORDEMSERVICO
    (
        ID NUMBER(10) NOT NULL,
        JUSTIFICATIVA VARCHAR2(1000),
        ATIVO NUMBER(10) NOT NULL,
        PRIMARY KEY (ID)
    );
    
CREATE TABLE
    MF_ORDEMSERVICO_MF_MATERIAL
    (
        ID NUMBER(10) NOT NULL,
        ATIVO NUMBER(10),
        QUANTIDADE_SOLICITADA NUMBER NOT NULL,
        QUANTIDADE_ENTREGUE NUMBER NOT NULL,
        QUANTIDADE_PENDENTE NUMBER NOT NULL,
        ID_ORDEM_SERVICO NUMBER(10) NOT NULL,
        ID_MATERIAL NUMBER(10) NOT NULL,
        PRIMARY KEY (ID),
        CONSTRAINT OS_MAT_FK1 FOREIGN KEY (ID_ORDEM_SERVICO) REFERENCES MF_ORDEMSERVICO (ID),
        CONSTRAINT OS_MAT_FK2 FOREIGN KEY (ID_MATERIAL) REFERENCES MF_MATERIAL (ID)
    ); 
    

CREATE SEQUENCE "ORDEMSERVICO_MATERIAL_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE     

ALTER TABLE MF_MATERIAL ADD (ESTOQUE NUMBER)