ALTER TABLE MF_ORDEMDECOMPRA DROP COLUMN AUTORIZADOR;
ALTER TABLE MF_ORDEMDECOMPRA DROP COLUMN CONTRATADO;
ALTER TABLE MF_ORDEMDECOMPRA ADD (ID_USUARIO NUMBER);
ALTER TABLE MF_ORDEMDECOMPRA ADD (ID_FORNECEDOR NUMBER);
ALTER TABLE MF_ORDEMDECOMPRA ADD CONSTRAINT MF_ORDEMDECOMPRA_fk1 FOREIGN KEY (ID_USUARIO) REFERENCES SYSAID_USER (ID);
ALTER TABLE MF_ORDEMDECOMPRA ADD CONSTRAINT MF_ORDEMDECOMPRA_fk2 FOREIGN KEY (ID_FORNECEDOR) REFERENCES COMPANY (ID);


ALTER TABLE MF_MATERIAL ADD (CODIGOBARRA VARCHAR2(255));
ALTER TABLE MF_MATERIAL MODIFY (DESCRICAO VARCHAR2(255));
ALTER TABLE MF_MATERIAL MODIFY (MATERIAL VARCHAR2(255));

29/07
ALTER TABLE MF_ORDEMDECOMPRA ADD (JUSTIFICATIVA VARCHAR2(1000));

30/07
ALTER TABLE MF_NOTAFISCAL ADD (JUSTIFICATIVA VARCHAR2(1000));

