

ALTER TABLE MF_APLICACAO ADD (user_name_responsavel VARCHAR2(255));
ALTER TABLE MF_APLICACAO MODIFY (DESCRICAO VARCHAR2(255));
ALTER TABLE MF_APLICACAO ADD CONSTRAINT MF_APLICACAO_fk1 FOREIGN KEY (user_name_responsavel) REFERENCES SYSAID_USER (USER_NAME);