
INSERT INTO MF_PARAMETRO (ID, QTDMESES) VALUES (1,1);
INSERT INTO COMPANY (COMPANY_ID, COMPANY_NAME) VALUES (1,'Company Teste');
INSERT INTO SYSAID_USER (USER_NAME, FIRST_NAME, LAST_NAME) VALUES (1,'José','Silva');