--------------------------------------------------------	
#NAME?	
--------------------------------------------------------	
--------------------------------------------------------	
#NAME?	
--------------------------------------------------------	
	
  CREATE TABLE "SYSAID"."MF_ENDERECO_HIERARQUIA" 	
   (	VALUE_KEY NUMBER, 
	AGRUPADOR VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 	
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 	
 NOCOMPRESS LOGGING	
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645	
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1	
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)	
  TABLESPACE "USERS" ;	
REM INSERTING into SYSAID.MF_ENDERECO_HIERARQUIA	
SET DEFINE OFF;	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('151','ABIN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('10','ANEXO I');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('11','ANEXO I');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('12','ANEXO I');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('13','ANEXO I');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('14','ANEXO II');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('15','ANEXO II');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('16','ANEXO II');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('17','ANEXO II');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('18','ANEXO III');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('19','ANEXO III');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('20','ANEXO III');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('21','ANEXO III');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('22','ANEXO IV');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('23','ANEXO IV');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('42','CCBB');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('43','CCBB');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('44','SAC');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('24','Complexo N2');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('25','Complexo N2');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('141','Complexo N2');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('140','Complexo N2');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('26','Complexo N2');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('27','Complexo N2');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('142','Complexo N2');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('28','Complexo N2');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('49','Edificio Darci Ribeiro');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('50','Edificio Varig');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('45','Escritório Boa Vista');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('46','Escritório Campinas');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('47','Escritório Porto Alegre');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('48','Escritório São Paulo');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('30','Esplanada Bloco A');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('31','Esplanada Bloco A');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('32','Esplanada Bloco A');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('33','Esplanada Bloco A');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('34','Esplanada Bloco O');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('35','Esplanada Bloco O');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('36','Esplanada Bloco O');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('51','EXPR');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('37','Gabinete Belo Horizonte');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('38','Gabinete Porto Alegre');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('39','Gabinete Rio de Janeiro');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('40','Granja do Torto');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('41','Granja do Torto');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('138','Imprensa Nacional');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('52','Instituto Cidadania');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('55','Instituto FHC');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('139','ITI');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('134','Outros');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('2','Palácio da Alvorada');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('1','Palácio da Alvorada');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('3','Palácio da Alvorada');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('4','Palácio do Jaburu');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('135','Palácio do Planalto');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('5','Palácio do Planalto');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('6','Palácio do Planalto');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('7','Palácio do Planalto');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('8','Palácio do Planalto');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('9','Palácio do Planalto');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('137','Pavilhão das Metas');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('146','SAUS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('53','SENAD');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('54','SENADO');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('136','SEPPIR');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('143','SAS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('29','COSAU');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('133','SHIS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('56','SMLN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('57','SPM');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('58','SQN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('59','SQN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('60','SQN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('61','SQN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('62','SQN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('63','SQN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('64','SQN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('65','SQN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('66','SQN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('67','SQN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('68','SQN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('69','SQN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('70','SQN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('71','SQN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('72','SQN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('73','SQN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('75','SQN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('74','SQN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('76','SQN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('77','SQN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('78','SQN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('79','SQN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('80','SQN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('81','SQN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('82','SQN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('83','SQN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('84','SQN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('85','SQN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('86','SQN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('87','SQN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('88','SQN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('89','SQN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('90','SQN');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('91','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('92','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('93','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('94','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('95','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('96','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('97','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('98','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('99','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('100','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('101','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('102','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('103','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('104','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('105','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('106','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('107','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('108','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('109','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('110','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('111','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('112','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('113','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('114','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('115','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('116','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('117','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('118','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('119','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('120','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('121','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('122','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('123','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('124','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('125','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('126','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('127','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('128','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('129','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('130','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('131','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('132','SQS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('148','SRTVS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('149','SRTVS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('150','SRTVS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('144','SRTVS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('145','SRTVS');	
Insert into SYSAID.MF_ENDERECO_HIERARQUIA (VALUE_KEY,AGRUPADOR) values ('147','SRTVS');	
--------------------------------------------------------	
#NAME?	
--------------------------------------------------------	
	
  CREATE UNIQUE INDEX "SYSAID"."MF_ENDERECO_HIERARQUIA_PK" ON "SYSAID"."MF_ENDERECO_HIERARQUIA" ("VALUE_KEY") 	
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 	
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645	
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1	
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)	
  TABLESPACE "USERS" ;	
--------------------------------------------------------	
#NAME?	
--------------------------------------------------------	
	
  ALTER TABLE "SYSAID"."MF_ENDERECO_HIERARQUIA" ADD CONSTRAINT "MF_ENDERECO_HIERARQUIA_PK" PRIMARY KEY ("VALUE_KEY")	
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 	
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645	
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1	
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)	
  TABLESPACE "USERS"  ENABLE;	
  ALTER TABLE "SYSAID"."MF_ENDERECO_HIERARQUIA" MODIFY ("AGRUPADOR" NOT NULL ENABLE);	
  ALTER TABLE "SYSAID"."MF_ENDERECO_HIERARQUIA" MODIFY ("VALUE_KEY" NOT NULL ENABLE);	